// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkm4U8rbgVuwaTBfLAMoSy0qSoS2-uUhw',
    appId: '1:559305489287:web:7fbe8ff6ea5b99a1457122',
    messagingSenderId: '559305489287',
    projectId: 'myapp-49a87',
    authDomain: 'myapp-49a87.firebaseapp.com',
    storageBucket: 'myapp-49a87.appspot.com',
    measurementId: 'G-2L72SR36MW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsg1QP4-WsejSmqO56skxwEI8YQ5Wq7T0',
    appId: '1:559305489287:android:6e16318891193298457122',
    messagingSenderId: '559305489287',
    projectId: 'myapp-49a87',
    storageBucket: 'myapp-49a87.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAOOgFRdjTiOZ7RkHThtDYVatLdo5_XeA',
    appId: '1:559305489287:ios:1285addd28e45aa8457122',
    messagingSenderId: '559305489287',
    projectId: 'myapp-49a87',
    storageBucket: 'myapp-49a87.appspot.com',
    iosClientId: '559305489287-ur7akufah01707fc66ec2qb0np3d01nv.apps.googleusercontent.com',
    iosBundleId: 'com.ankita.whattsup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAOOgFRdjTiOZ7RkHThtDYVatLdo5_XeA',
    appId: '1:559305489287:ios:46910c8feb0cf810457122',
    messagingSenderId: '559305489287',
    projectId: 'myapp-49a87',
    storageBucket: 'myapp-49a87.appspot.com',
    iosClientId: '559305489287-9mb1h4faljiaffpcem23fbo09111k0jm.apps.googleusercontent.com',
    iosBundleId: 'com.ankita.whattsup.RunnerTests',
  );
}
